import Link from 'next/link';
import { ChefHat } from 'lucide-react';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50 dark:bg-gray-950">
      <nav className="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center gap-4">
          <Link href="/" className="flex items-center gap-2">
            <ChefHat className="h-6 w-6 text-green-600" />
            <span className="text-lg font-bold text-gray-900 dark:text-white">Petra AI</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-16 prose prose-gray dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-gray-500 dark:text-gray-400 text-sm">Last updated: September 7, 2025</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Petra AI ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>Petra AI provides an AI-powered kitchen management platform including recipe discovery, meal planning, pantry tracking, and shopping list generation. Some features require a paid subscription.</p>

        <h2>3. User Accounts</h2>
        <p>You must create an account to use the Service. You are responsible for maintaining the security of your account and for all activities that occur under your account.</p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to use the Service for any unlawful purpose or in any way that could harm other users, our systems, or third parties.</p>

        <h2>5. Subscriptions & Payments</h2>
        <p>Premium features require a paid subscription. Subscriptions are billed monthly and can be cancelled at any time. No refunds are provided for partial months.</p>

        <h2>6. AI-Generated Content</h2>
        <p>Recipes and meal plans generated by AI are provided for informational purposes. Always exercise your own judgment about nutritional information and food safety.</p>

        <h2>7. Intellectual Property</h2>
        <p>The Service and its original content are owned by Petra AI and protected by copyright and other intellectual property laws.</p>

        <h2>8. Limitation of Liability</h2>
        <p>Petra AI shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>

        <h2>9. Changes to Terms</h2>
        <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

        <h2>10. Contact</h2>
        <p>Questions about these Terms? Contact us at <a href="mailto:legal@petra.ai">legal@petra.ai</a>.</p>
      </div>
    </main>
  );
}
